# Generated by Django 6.0.6 on 2026-08-22 20:16

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('SOCIAL', 'social'), ('INTERVIEW', 'Interview'), ('ARTICLE', 'Article')], default='SOCIAL', max_length=20, verbose_name='Post Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='Video')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('category', models.CharField(blank=True, choices=[('INTERVIEW', 'Interview'), ('ALGORITHM', 'Algorithm'), ('SYSTEM_DESIGN', 'System Design'), ('SQL', 'SQL'), ('BACKEND', 'backend'), ('LINUX', 'linux')], default='INTERVIEW', max_length=20, null=True, verbose_name='Category')),
                ('difficulty', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20, null=True, verbose_name='Difficulty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.company', verbose_name='Company')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='posts_post_slug_59b922_idx'), models.Index(fields=['created_at'], name='posts_post_created_dadbfe_idx'), models.Index(fields=['category', 'difficulty'], name='posts_post_categor_05cae8_idx')],
            },
        ),
    ]
