# Generated by Django 6.0.6 on 2026-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_company_id_alter_post_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('INTERVIEW', 'Interview'), ('ALGORITHM', 'Algorithm'), ('SYSTEM_DESIGN', 'System Design'), ('SQL', 'SQL'), ('BACKEND', 'backend'), ('LINUX', 'linux')], default='INTERVIEW', max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20, null=True, verbose_name='Difficulty'),
        ),
    ]
