# Generated by Django 6.0.6 on 2026-08-04 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.CharField(choices=[('POST', 'New Post'), ('LIKE', 'Liked your Post'), ('COMMENT', 'Commented on your Post'), ('ANSWER', 'Answered your question'), ('FOLLOW', 'Follow You')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='interaction_user_id_11d0df_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='interaction_created_097a8a_idx'),
        ),
    ]
