# Generated by Django 6.0.6 on 2026-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_alter_notification_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.CharField(choices=[('POST', 'New Post'), ('LIKE', 'Liked your Post'), ('COMMENT', 'Commented on your Post'), ('ANSWER', 'Answered your question'), ('FOLLOW', 'Follow You'), ('BOOKMARK', 'Bookmarked your post')], max_length=20),
        ),
    ]
