# Generated by Django 6.0.6 on 2026-07-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatar/default.jpg', null=True, upload_to='avatars/', verbose_name='Profile Picture'),
        ),
    ]
